# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 05:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='aircraft')),
                ('n_number', models.CharField(max_length=10, null=True)),
                ('model', models.CharField(max_length=255, null=True)),
                ('location_identifier', models.CharField(max_length=5, null=True)),
                ('equipment', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=25, null=True)),
                ('true_air_speed_knots', models.CharField(max_length=25, null=True)),
                ('hp', models.IntegerField()),
                ('useful_load', models.IntegerField()),
                ('price_per_hour_usd', models.IntegerField()),
                ('misc_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AirworthinessDirective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, null=True)),
                ('next_due_date', models.DateField()),
                ('days_interval', models.IntegerField()),
                ('tach_interval', models.IntegerField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.Aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallons_at_start', models.IntegerField(null=True)),
                ('ending_tach', models.FloatField(null=True)),
                ('ending_hobbs', models.FloatField(null=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.Aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('color', models.IntegerField()),
                ('description', models.TextField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.Aircraft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='scheduling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.Scheduling'),
        ),
        migrations.AddField(
            model_name='flight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
