# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 03:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('medical_expiration', models.DateField(null=True)),
                ('bfr', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('bfr_expiration', models.DateField(null=True)),
                ('claims', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('drivers_license', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('felonies_misdemeanors', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('insurance_history', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('truthful', models.BooleanField(default=False)),
                ('printed_name', models.CharField(max_length=100, null=True)),
                ('submitted_at', models.DateField(blank=True, default=datetime.datetime.now)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occured_at', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('drivers_license_report', models.FileField(null=True, upload_to='documents/%Y/%m/%d/')),
                ('birth_date', models.DateField(null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('state_abbreviation', models.CharField(max_length=2, null=True)),
                ('zipcode', models.CharField(max_length=9, null=True)),
                ('criminal_convictions', models.TextField(blank=True, null=True)),
                ('united_states_citizen', models.BooleanField(default=False)),
                ('if_no_where', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('commercial', models.BooleanField(default=False)),
                ('atp', models.BooleanField(default=False)),
                ('cfi', models.BooleanField(default=False)),
                ('other', models.CharField(blank=True, max_length=100, null=True)),
                ('faa_certificate_number', models.CharField(max_length=10, null=True)),
                ('total_flight_hours', models.CharField(max_length=4, null=True)),
                ('bfr_expiration', models.DateField(null=True)),
                ('medical_expiration', models.DateField(null=True)),
                ('reference_name', models.CharField(max_length=100, null=True)),
                ('reference_relation', models.CharField(max_length=30, null=True)),
                ('reference_phone', models.CharField(max_length=11, null=True)),
                ('information_verified_by', models.CharField(max_length=30, null=True)),
                ('inconsistencies', models.TextField(null=True)),
                ('notes', models.TextField(null=True)),
                ('approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_text', models.TextField()),
                ('minutes_file', models.FileField(upload_to='')),
                ('minutes_date', models.DateTimeField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Minutes',
            },
        ),
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(null=True)),
                ('made_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motions_made', to=settings.AUTH_USER_MODEL)),
                ('seconded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motions_seconded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublicDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('uploaded_file', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, default=False, max_length=2000)),
                ('yes_or_no_response', models.BooleanField(default=False)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve', models.BooleanField(default=False)),
                ('detail', models.CharField(blank=True, default=False, max_length=2000)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.SurveyQuestion')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yay', models.BooleanField(default=False)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_made', to='club.Motion')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Minutes'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Meeting'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
