# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-25 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_auto_20151125_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='motion',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
