# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-12-29 01:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_motion_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='question',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='yes_or_no_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='detail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='yay',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='motion',
            name='seconded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motions_seconded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='motion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_made', to='club.Motion'),
        ),
    ]
