# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-12-29 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_auto_20151229_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='question',
            field=models.CharField(blank=True, default=False, max_length=2000),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='detail',
            field=models.CharField(blank=True, default=False, max_length=2000),
        ),
    ]
