# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-12-31 02:36
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0010_auto_20151229_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical', models.BooleanField(default=False)),
                ('medical_expiration', models.DateField(null=True)),
                ('bfr', models.BooleanField(default=False)),
                ('bfr_expiration', models.DateField(null=True)),
                ('claims', models.BooleanField(default=False)),
                ('drivers_license', models.BooleanField(default=False)),
                ('felonies_misdemeanors', models.BooleanField(default=False)),
                ('insurance_history', models.BooleanField(default=False)),
                ('truthful', models.BooleanField(default=False)),
                ('printed_name', models.CharField(max_length=100, null=True)),
                ('submitted_at', models.DateField(blank=True, default=datetime.datetime.now)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
