# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-01-24 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_insurancesurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='argument',
            field=models.TextField(blank=True, null=True),
        ),
    ]
