# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-05-03 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_auto_20160124_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('uploaded_file', models.FileField(null=True, upload_to=b'')),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='argument',
        ),
        migrations.AlterField(
            model_name='vote',
            name='yay',
            field=models.BooleanField(default=False),
        ),

    ]
